// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2g9-_zCytsGcXca384VD3LSe6kxtyV8E',
    appId: '1:221372666775:web:45ff6d6ea765df6d172ad2',
    messagingSenderId: '221372666775',
    projectId: 'taskmanagement-6ce7f',
    authDomain: 'taskmanagement-6ce7f.firebaseapp.com',
    storageBucket: 'taskmanagement-6ce7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG5bTxhtyrGqSWBePgFTAb9GioUQDobrw',
    appId: '1:221372666775:android:168c790b8ccbf97d172ad2',
    messagingSenderId: '221372666775',
    projectId: 'taskmanagement-6ce7f',
    storageBucket: 'taskmanagement-6ce7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqjsu2uS4ofLqyVxV90RU4N_5BbAXNpHw',
    appId: '1:221372666775:ios:18192cf7f568ae9e172ad2',
    messagingSenderId: '221372666775',
    projectId: 'taskmanagement-6ce7f',
    storageBucket: 'taskmanagement-6ce7f.appspot.com',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqjsu2uS4ofLqyVxV90RU4N_5BbAXNpHw',
    appId: '1:221372666775:ios:42bc90f6e3ff005e172ad2',
    messagingSenderId: '221372666775',
    projectId: 'taskmanagement-6ce7f',
    storageBucket: 'taskmanagement-6ce7f.appspot.com',
    iosBundleId: 'com.example.todolistapp.RunnerTests',
  );
}
